### PR TITLE
Master

### PR DESCRIPTION
**Pull request by simonhac**
added .enable and .disable functions to individual log channels

### CODE REVIEW

**Comment by simonhac** [comment]
hmmmm, build is failing. works locally, but i had a hell of a time fighting dependencies.
let me look into it...

**Comment by simonhac** [comment]
@tehsenaus hi -- i've been using hot-debug for a few days now and really appreciate it. thank you!

here's a change i've put together that allows the user to enable/disable individual channels at runtime without messing with other channels. (there's one corner case with wildcards that doesn't work, but fails gracefully.)

as i'm new to JS, please excuse that i've got stuck on a few things:
* i am not familiar with mocha (i realise that it is incredibly popular!) however i was convinced to start with [tape](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.owc2bok9d). i took a look at mocha (after i'd written my tests) and i'd prefer to leave them in tape if that's ok. (i ported your test from mocha to tape.)
* as alluded to above, i blew a day in dependency hell today. for some reason `npm` on my local machine doesn't install the right version of `debug` -- even though the package file stipulates `debug@>=2.4.0` it skips it and IIRC falls back to v2.2.0 (pulled in by mocha):
image

when i manually install `debug` it works just fine.

as you can see above, travis is having trouble with my changes -- they work with 2 of the configurations tested, but fail with the other 5. i'll take a look tomorrow, but if you have any familiarity with this problem, i'd greatly appreciate any help.

ps. i debugged it locally by setting `DEBUG_ENV=module` and browsing through the logs. that's the first thing i'll try tomorrow.

**Comment by simonhac** [comment]
yay! the primary issue i was having was that `peerDependency` has been deprecated. @tehsenaus, now that i have a fully working build, please consider merging.

**Comment by tehsenaus** [comment]
Hi, thanks for taking the time to put this together!

I will review this evening and get back to you.

**Comment by simonhac** [comment]
thanks @tehsenaus -- as discussed above, i ran into several tricky dependency issues with `hot-debug`, specifically when there were several versions of `debug` in the modules hierarchy.

would you consider changing `hot-debug` so that the syntax was more like:

```javascript
const log = require('hot-debug')('my-channel');
```

instead of:
```javascript
require('../hot-debug.js');
const log = require('debug')('my-channel');
```

...or is there another way of ensuring that the dependencies are properly managed. (see my comment above that `peerDependencies` have been deprecated.)

**Comment by simonhac** [comment]
hi @tehsenaus, did you get a chance to check out this PR yet?

**Comment by tehsenaus** [comment]
Hi @simonhac,

Thanks for taking the time to submit this.

It's a rather big change though for what it's adding, and I think I'd rather keep the scope of this library fixed to just enabling hot enable/disable with no API changes over debug.

You should publish this as your own module though - small, focused modules are what node is all about!

Thanks,
Sean

**Comment by tehsenaus** [comment]
On the dependency issues - my understanding is that now peerDependencies are advisory only. The expectation is that the user is already importing debug either directly or indirectly through other dependencies.

**Comment by simonhac** [comment]
thanks @tehsenaus -- i thought the change to index.js was pretty modest, but i'm happy to fork, rename and push to NPM if you're more comfortable with that.
i'll let you know when i've got around to it. thanks!

**Comment by simonhac** [comment]
on the dependency issues -- the problem i had is if the project ended up loading multiple versions of debug, which is easily possible.

**Pull request closed without merging**
